-- Business Opportunities Seed — adapted to existing table schema
-- Columns: title, description, type, source, value_min, value_max,
--          eligibility, status, is_client_facing, metadata, opportunity_type,
--          niche, evidence_summary, monetization_hint, urgency, confidence, score

INSERT INTO public.business_opportunities
  (title, description, type, source, value_min, value_max,
   eligibility, status, is_client_facing, opportunity_type, niche,
   evidence_summary, monetization_hint, urgency, confidence, score,
   metadata)
VALUES
  (
    'AI Content Agency',
    'Start an AI-powered content agency serving local businesses. Use Claude/ChatGPT to produce blogs, social posts, ad copy, and email campaigns at scale.',
    'business_model',
    'market_research',
    0, 500,
    'Anyone with basic writing + prompt skills',
    'active',
    true,
    'service_business',
    'ai_content',
    'Hundreds of solo operators validated on X/Twitter earning $2K-15K/month',
    'Monthly retainer $500-2000/client; scale with AI tooling',
    'high',
    0.90,
    9,
    '{"startup_cost_range": "$0-$500", "time_to_launch_weeks": 2, "skills": "Prompt engineering, basic marketing", "first_step": "Offer free sample to 3 local businesses", "nexus_fit": 9, "risk": "low"}'
  ),
  (
    'Credit Repair Consulting',
    'Non-regulated credit repair consulting helping clients understand and dispute credit report errors. Must follow CROA — no upfront fees.',
    'business_model',
    'market_research',
    0, 1500,
    'Service providers; must comply with Credit Repair Organizations Act (CROA)',
    'active',
    true,
    'financial_service',
    'credit_repair',
    'High demand niche; millions of Americans need credit repair. $500-1500/month per client retainer.',
    'Monthly retainer model; credit repair software $100-200/month',
    'high',
    0.95,
    10,
    '{"startup_cost_range": "$200-$500", "time_to_launch_weeks": 3, "skills": "Credit fundamentals, dispute process", "first_step": "Get certified through Credit Consultants Association", "nexus_fit": 10, "risk": "medium"}'
  ),
  (
    'Business Funding Broker / ISO Agent',
    'Refer small businesses to MCA, SBA, and alternative lenders. Earn 1-3% referral fee on funded deals. ISO agreements with multiple lenders.',
    'business_model',
    'market_research',
    200, 500,
    'Requires ISO agreements; some states require licensing. Not available in all states.',
    'active',
    true,
    'financial_service',
    'business_funding',
    'Alternative lending market has thousands of successful brokers. $500-10K+ per funded deal.',
    'Commission per funded deal; 1-3% of loan amount',
    'high',
    0.95,
    10,
    '{"startup_cost_range": "$200-$500", "time_to_launch_weeks": 3, "skills": "Lending products, ISO agreements", "first_step": "Connect with Credibly, OnDeck, Fundbox for ISO agreements", "nexus_fit": 10, "risk": "medium"}'
  ),
  (
    'LLC Setup / Business Formation Service',
    'Help entrepreneurs set up LLCs, obtain EINs, open business bank accounts, and establish business credit. Non-legal service (no legal advice).',
    'business_model',
    'market_research',
    200, 500,
    'Must not provide legal advice; clearly position as document/formation service',
    'active',
    true,
    'service_business',
    'business_formation',
    'Millions of entrepreneurs need help with business setup. $200-500 per client.',
    'One-time fee per setup; upsell to business credit building',
    'high',
    0.90,
    9,
    '{"startup_cost_range": "$200-$500", "time_to_launch_weeks": 2, "skills": "State formation procedures", "first_step": "Partner with a business attorney for referrals", "nexus_fit": 9, "risk": "low-medium"}'
  ),
  (
    'Digital Product Store (Etsy/Gumroad)',
    'Create and sell digital templates, planners, budget sheets, resume templates, and printables on Etsy or Gumroad. Passive income after catalog is built.',
    'business_model',
    'market_research',
    0, 100,
    'Open to everyone; Etsy listing fees apply',
    'active',
    true,
    'online_business',
    'digital_products',
    'Etsy bestsellers confirmed; Gumroad creator success stories. $500-5K/month passive after catalog.',
    'Digital download; 0 marginal cost per sale',
    'medium',
    0.85,
    8,
    '{"startup_cost_range": "$0-$100", "time_to_launch_weeks": 1, "skills": "Design basics, Canva, niche research", "first_step": "Create 20 templates in one niche", "nexus_fit": 8, "risk": "low"}'
  ),
  (
    'AI Bookkeeping Service',
    'Offer bookkeeping services to small businesses using AI-enhanced workflows (QuickBooks, AI categorization). $500-3K/month per client.',
    'business_model',
    'market_research',
    100, 300,
    'No CPA license required for basic bookkeeping (not tax prep)',
    'active',
    true,
    'service_business',
    'ai_bookkeeping',
    'High demand from small businesses avoiding $200/hr CPA fees. QuickBooks ProAdvisor certification is free.',
    'Monthly retainer $500-3000/client',
    'medium',
    0.85,
    8,
    '{"startup_cost_range": "$100-$300/month", "time_to_launch_weeks": 3, "skills": "Basic accounting, QuickBooks", "first_step": "Get QuickBooks ProAdvisor certification (free)", "nexus_fit": 8, "risk": "low-medium"}'
  ),
  (
    'SAM.gov Federal Government Contracting',
    'Register on SAM.gov and pursue federal small business contracts. $700B+ in US federal procurement annually. Set-aside opportunities for small businesses.',
    'business_model',
    'market_research',
    0, 500,
    'US business; SAM.gov registration required (free); some contracts require certifications',
    'active',
    true,
    'government_contracting',
    'federal_contracts',
    '$700B+ annual federal procurement. Small business set-asides guarantee portion goes to small businesses.',
    'Contract revenue; very high ceiling',
    'medium',
    0.80,
    8,
    '{"startup_cost_range": "$0-$500", "time_to_launch_weeks": 6, "skills": "Procurement knowledge, proposal writing", "first_step": "Register at SAM.gov; identify 5 relevant NAICS codes", "nexus_fit": 8, "risk": "medium"}'
  ),
  (
    'Social Media Management Agency',
    'Manage social media presence for local businesses. Schedule posts, respond to comments, run basic ad campaigns.',
    'business_model',
    'market_research',
    0, 200,
    'Open to anyone; scheduling tool subscriptions required',
    'active',
    true,
    'service_business',
    'social_media',
    'Millions of SMBs have no social presence. $1K-3K/month per client.',
    'Monthly management fee',
    'medium',
    0.80,
    8,
    '{"startup_cost_range": "$0-$200", "time_to_launch_weeks": 2, "skills": "Social media, writing, consistency", "first_step": "Offer 30-day free trial to 2 local businesses", "nexus_fit": 8, "risk": "low"}'
  ),
  (
    'Prompt Engineering Consulting',
    'Help businesses use AI tools effectively. Document prompting frameworks, train teams, build custom AI workflows.',
    'business_model',
    'market_research',
    0, 0,
    'Anyone with deep AI tool experience',
    'active',
    true,
    'consulting',
    'ai_prompting',
    'Growing demand as businesses struggle to use AI tools. $50-200/hour.',
    'Hourly or project-based consulting',
    'high',
    0.90,
    9,
    '{"startup_cost_range": "$0", "time_to_launch_weeks": 0, "skills": "Deep AI tool knowledge", "first_step": "Document 10 prompting frameworks and share on LinkedIn", "nexus_fit": 9, "risk": "low"}'
  ),
  (
    'Virtual Assistant Service (AI-Enhanced)',
    'Provide executive VA services using AI productivity tools (Slack, Notion, email automation, scheduling). Specialize in AI-enhanced workflows.',
    'business_model',
    'market_research',
    0, 100,
    'Open to anyone with strong organization and communication skills',
    'active',
    true,
    'service_business',
    'virtual_assistant',
    'Remote work explosion drove VA demand. $25-75/hour; $2-6K/month full-time.',
    'Hourly or monthly retainer',
    'medium',
    0.80,
    7,
    '{"startup_cost_range": "$0-$100", "time_to_launch_weeks": 1, "skills": "Organization, Slack, Notion, Gmail", "first_step": "List on Upwork; specialize in AI-enhanced productivity", "nexus_fit": 7, "risk": "low"}'
  ),
  (
    'Niche Affiliate Website',
    'Build a content website in a specific niche and earn affiliate commissions. Long-term passive income asset (6-18 months to build).',
    'business_model',
    'market_research',
    100, 500,
    'Open to anyone; requires patience and consistent content production',
    'active',
    true,
    'online_business',
    'affiliate_marketing',
    'Millions of successful affiliate sites. $500-10K+/month after traction.',
    'Affiliate commissions; display ads',
    'low',
    0.75,
    7,
    '{"startup_cost_range": "$100-$500", "time_to_launch_weeks": 8, "skills": "SEO, content writing, patience", "first_step": "Pick niche with <100K competing pages; write 20 articles", "nexus_fit": 7, "risk": "medium"}'
  ),
  (
    'Subcontracting with Prime Government Contractors',
    'Partner with large prime contractors (Booz Allen, Leidos, SAIC) as a small business sub. Provide IT, security, consulting, or admin services.',
    'business_model',
    'market_research',
    0, 500,
    'Must have a specific service skill; SAM.gov registration recommended',
    'active',
    true,
    'government_contracting',
    'subcontracting',
    'Large primes actively recruit small subs. $5-50K/month depending on skill.',
    'Subcontract revenue',
    'medium',
    0.80,
    8,
    '{"startup_cost_range": "$0-$500", "time_to_launch_weeks": 4, "skills": "A specific service skill (IT, security, admin)", "first_step": "Join SBA Matchmaking events; attend GSA outreach sessions", "nexus_fit": 8, "risk": "low-medium"}'
  ),
  (
    'Tradeline Reseller Business',
    'Sell authorized user positions on established credit accounts to help consumers build credit. Compliance-heavy gray area — legal review required.',
    'business_model',
    'market_research',
    500, 2000,
    'Must comply with CFPB and FTC guidelines; gray area — consult attorney before launch',
    'active',
    true,
    'financial_service',
    'tradelines',
    'Established industry. $2-20K/month potential. Requires compliance review.',
    'Per tradeline sale',
    'medium',
    0.70,
    7,
    '{"startup_cost_range": "$500-$2000", "time_to_launch_weeks": 3, "skills": "Credit tradeline knowledge, compliance", "first_step": "Research CFPB guidance; consult compliance attorney", "nexus_fit": 7, "risk": "medium-high"}'
  )
ON CONFLICT DO NOTHING;
