// ── Copilot Response Templates ────────────────────────────────────────────────
// Safe, pre-structured response formats for both copilot roles.
// All templates enforce the boundary that client-specific advice is
// escalated to human staff — never auto-generated by AI.
// ─────────────────────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

export const RESPONSE_TYPE = Object.freeze({
  KNOWLEDGE:   "knowledge",    // Found relevant info from knowledge base
  ESCALATION:  "escalation",   // Requires human staff involvement
  EMPTY:       "empty",        // No relevant knowledge found
  ERROR:       "error",        // System error (safe empty fallback)
  DRY_RUN:     "dry_run",      // Validation only, no actual response
});

// ── Empty state templates ─────────────────────────────────────────────────────

export const EMPTY_STATE_RESPONSES = Object.freeze({
  portal: {
    grant_lookup:
      "We're currently updating our grants database. Check back soon, or contact our team for personalized funding guidance.",
    business_ideas:
      "Our research team is adding new business opportunity content regularly. Contact us if you'd like a personalized consultation.",
    credit_guidance:
      "For credit guidance tailored to your situation, please speak with one of our advisors directly.",
    general_research:
      "I don't have specific information on that topic yet. Our team is continuously building out the knowledge base.",
  },
  staff: {
    crm_insight:
      "No CRM automation research found for this query. Run the research pipeline with topic=crm_automation.",
    grant_summary:
      "No grant opportunities found above threshold. Run GrantWorker to process recent artifacts.",
    opportunity_summary:
      "No business opportunities found. Run OpportunityWorker with --since 30.",
    general_research:
      "No relevant research found. Check that research_artifacts table is populated.",
  },
});

// ── Escalation templates ──────────────────────────────────────────────────────

export const ESCALATION_RESPONSES = Object.freeze({
  account_specific:
    "This question relates to your specific account. A Nexus team member will follow up with you directly.",
  credit_report:
    "Credit report reviews require working directly with our advisors to protect your personal information.",
  billing:
    "Billing and payment questions are handled by our team. Please contact us directly.",
  sensitive_dispute:
    "Dispute-specific guidance requires a personal consultation. Our team will reach out to assist you.",
  default:
    "This question requires personalized attention. A team member will be in touch shortly.",
});

// ── Response builders ─────────────────────────────────────────────────────────

/**
 * Build a portal response from structured knowledge.
 * @param {Object} opts
 * @param {string} opts.intent
 * @param {Array} opts.knowledge
 * @param {boolean} [opts.escalated=false]
 * @returns {Object}
 */
export function buildPortalKnowledgeResponse({ intent, knowledge = [], escalated = false }) {
  if (escalated) {
    return {
      type: RESPONSE_TYPE.ESCALATION,
      message: ESCALATION_RESPONSES[intent] ?? ESCALATION_RESPONSES.default,
      knowledge_used: [],
      escalated: true,
      requires_human_follow_up: true,
    };
  }

  if (!knowledge.length) {
    return {
      type: RESPONSE_TYPE.EMPTY,
      message: EMPTY_STATE_RESPONSES.portal[intent] ?? EMPTY_STATE_RESPONSES.portal.general_research,
      knowledge_used: [],
      escalated: false,
      requires_human_follow_up: false,
    };
  }

  const bullets = knowledge.slice(0, 3).map((k) => {
    if (k.funding_amount) return `${k.title} — ${k.funding_amount}${k.deadline ? ` (Deadline: ${k.deadline})` : ""}`;
    if (k.opportunity_type) return `${k.title} — ${k.niche ?? k.opportunity_type}`;
    return k.title ?? k.summary?.slice(0, 80) ?? "Resource";
  });

  return {
    type: RESPONSE_TYPE.KNOWLEDGE,
    message: `Here's what we found:\n\n${bullets.map((b) => `• ${b}`).join("\n")}\n\nFor personalized guidance, reach out to our team.`,
    knowledge_used: knowledge.map((k) => k.title ?? "item"),
    escalated: false,
    requires_human_follow_up: false,
  };
}

/**
 * Build a staff response from structured knowledge.
 * @param {Object} opts
 * @param {string} opts.intent
 * @param {Array} opts.knowledge
 * @param {string} [opts.summary]
 * @returns {Object}
 */
export function buildStaffKnowledgeResponse({ intent, knowledge = [], summary }) {
  if (!knowledge.length) {
    return {
      type: RESPONSE_TYPE.EMPTY,
      message: EMPTY_STATE_RESPONSES.staff[intent] ?? EMPTY_STATE_RESPONSES.staff.general_research,
      knowledge_used: [],
      item_count: 0,
    };
  }

  const items = knowledge.map((k) => ({
    title: k.title ?? "Untitled",
    detail: k.score ? `Score: ${k.score}` : k.niche ?? k.opportunity_type ?? k.topic ?? "",
    source: k.source ?? null,
  }));

  return {
    type: RESPONSE_TYPE.KNOWLEDGE,
    message: summary ?? `Found ${items.length} item(s) matching your query.`,
    items,
    knowledge_used: items.map((i) => i.title),
    item_count: items.length,
  };
}

/**
 * Build a safe error response (never expose system internals).
 * @param {string} [userFacingMessage]
 * @returns {Object}
 */
export function buildErrorResponse(userFacingMessage) {
  return {
    type: RESPONSE_TYPE.ERROR,
    message: userFacingMessage ?? "Something went wrong. Please try again or contact our team.",
    knowledge_used: [],
  };
}
