from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Callable

from notifications.operator_notifications import send_operator_email
from scripts.prelaunch_utils import rest_select

SEND_ENABLED = os.getenv("EMAIL_COMMAND_SEND_ENABLED", "false").lower() == "true"
MAX_ARTIFACTS = int(os.getenv("EMAIL_COMMAND_MAX_RESEARCH_ARTIFACTS", "3"))


def _safe_select(path: str) -> list[dict[str, Any]]:
    try:
        return rest_select(path, timeout=10) or []
    except Exception:
        return []


def latest_research_artifacts(limit: int = MAX_ARTIFACTS) -> list[dict[str, Any]]:
    rows = _safe_select(
        "research_artifacts?select=title,topic,summary,key_points,action_items,opportunity_notes,risk_warnings,created_at"
        f"&order=created_at.desc&limit={max(1, min(limit, 5))}"
    )
    return rows


def latest_executive_brief(briefing_type: str | None = None) -> dict[str, Any] | None:
    query = "executive_briefings?select=briefing_type,content,urgency,generated_by,created_at"
    if briefing_type:
        query += f"&briefing_type=eq.{briefing_type}"
    query += "&order=created_at.desc&limit=1"
    rows = _safe_select(query)
    return rows[0] if rows else None


def help_text() -> str:
    return (
        "Research email commands\n\n"
        "Use one of these in the email body:\n"
        "- preview latest research summary\n"
        "- send latest research summary\n"
        "- preview latest funding brief\n"
        "- send latest funding brief\n"
        "- help\n\n"
        "Safety:\n"
        "- preview does not send outbound email\n"
        "- send uses the stored latest summary/brief only\n"
        "- no research pipeline rerun happens from these commands"
    )


def _format_research_body(rows: list[dict[str, Any]]) -> tuple[str, str]:
    if not rows:
        return (
            "Nexus Research Summary Unavailable",
            "No stored research artifacts were found yet.\n\nNothing was sent.",
        )

    body_lines = [
        f"Nexus Research Summary",
        f"Generated from stored artifacts at {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]
    for idx, row in enumerate(rows, 1):
        body_lines.append(f"{idx}. {row.get('title') or 'Untitled'}")
        body_lines.append(f"Category: {(row.get('topic') or 'general').replace('_', ' ').title()}")
        body_lines.append(f"Summary: {row.get('summary') or 'No summary available.'}")
        action_items = row.get("action_items") or []
        if action_items:
            body_lines.append("Action items:")
            for item in action_items[:3]:
                body_lines.append(f"- {item}")
        body_lines.append("")

    body_lines.append("Source: stored research artifacts only. No pipeline rerun was triggered.")
    return "Nexus Research Summary", "\n".join(body_lines).strip()


def _format_brief_body(row: dict[str, Any] | None, label: str) -> tuple[str, str]:
    if not row:
        return (
            f"Nexus {label} Unavailable",
            f"No stored {label.lower()} was found yet.\n\nNothing was sent.",
        )
    subject = f"Nexus {label}"
    body = (
        f"{label}\n"
        f"Stored at: {row.get('created_at') or 'unknown'}\n"
        f"Urgency: {row.get('urgency') or 'unknown'}\n"
        f"Generated by: {row.get('generated_by') or 'unknown'}\n\n"
        f"{row.get('content') or 'No content available.'}"
    )
    return subject, body


def build_email_preview(command_text: str) -> dict[str, Any]:
    normalized = (command_text or "").strip().lower()
    if normalized in {"help", ""}:
        return {"ok": True, "mode": "help", "subject": "Research email commands", "body": help_text()}

    if normalized in {"preview latest research summary", "preview research email"}:
        subject, body = _format_research_body(latest_research_artifacts())
        return {"ok": True, "mode": "preview", "command": normalized, "subject": subject, "body": body}

    if normalized in {"preview latest funding brief", "preview funding brief"}:
        subject, body = _format_brief_body(latest_executive_brief("funding"), "Funding Brief")
        return {"ok": True, "mode": "preview", "command": normalized, "subject": subject, "body": body}

    if normalized in {"send latest research summary", "send research email"}:
        subject, body = _format_research_body(latest_research_artifacts())
        return {"ok": True, "mode": "send", "command": normalized, "subject": subject, "body": body}

    if normalized in {"send latest funding brief", "send funding brief"}:
        subject, body = _format_brief_body(latest_executive_brief("funding"), "Funding Brief")
        return {"ok": True, "mode": "send", "command": normalized, "subject": subject, "body": body}

    return {
        "ok": False,
        "mode": "unknown",
        "subject": "Unknown research email command",
        "body": help_text(),
    }


def execute_email_command(
    command_text: str,
    *,
    send_enabled: bool = SEND_ENABLED,
    sender: Callable[[str, str], tuple[bool, str]] = send_operator_email,
) -> dict[str, Any]:
    preview = build_email_preview(command_text)
    if preview.get("mode") != "send":
        return preview

    if not send_enabled:
        preview["ok"] = False
        preview["send_blocked"] = True
        preview["body"] += "\n\nSend is disabled by policy. Preview only."
        return preview

    sent, detail = sender(preview["subject"], preview["body"])
    preview["sent"] = sent
    preview["detail"] = detail
    preview["ok"] = sent
    return preview
