#!/usr/bin/env python3
"""
Nexus Monetization Scout runner.

- --analyze "<text>"  /  --file <path> : treat the text as PRIMARY evidence and
  print the 12-part Nexus-first monetization scout response (the re-run test).
- --build-sample-pack : create ONE sample "30-Day AI Content Growth Pack" draft
  locally + register each piece as a reviewable showroom asset (needs_review).
- --notify [--dry-run] : Ray-only showroom notification (dry-run default).

Local-only: no publish, no email, no Stripe, no affiliate, no paid API, no deploy.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from lib import hermes_monetization_scout as SCOUT  # noqa: E402

PACK_DIR = ROOT / "reports" / "content_engine" / "generated" / "monetization_packs"
SAMPLE = "30day_ai_content_growth_pack_sample"


def build_sample_pack() -> list[Path]:
    PACK_DIR.mkdir(parents=True, exist_ok=True)
    pieces = {
        f"{SAMPLE}_README.md": "# 30-Day AI Content Growth Pack — SAMPLE (draft, not published)\n\n"
        "Target: small business owners, coaches, consultants, funding/credit pros, local services, agencies.\n"
        "Deliverables: 4 newsletters · 8 short-video scripts · 4 social posts · 1 landing page draft · "
        "1 lead-magnet outline · 1 content strategy summary.\nBeta pricing: $197 beta (or $297 setup + $497/mo after validation).\n"
        "Status: draft for Ray review. No public publishing, no emails, no Stripe until Ray approves.\n",
        f"{SAMPLE}_newsletters.md": "# 4 Newsletter Drafts (sample)\n\n1. \"3 customers you're forgetting to win back\"\n"
        "2. \"The boring content system that beats going viral\"\n3. \"What we'd post for your business this week\"\n"
        "4. \"One offer, four ways to say it\"\n(Drafts only — bodies generated by the content engine.)\n",
        f"{SAMPLE}_video_scripts.md": "# 8 Short-Form Video Scripts (sample hooks)\n\n"
        + "\n".join(f"{i}. Hook + 20s script slot {i}" for i in range(1, 9)) + "\n",
        f"{SAMPLE}_social_posts.md": "# 4 Social Posts (sample)\n\n1. ... 2. ... 3. ... 4. ...\n(No financial/guarantee claims.)\n",
        f"{SAMPLE}_landing_page.md": "# Landing Page Draft (sample)\n\nHeadline: \"Consistent, on-brand marketing content "
        "every month — without hiring a team or learning AI tools.\"\nCTA: Start the 30-Day Pack (beta).\n",
        f"{SAMPLE}_lead_magnet.md": "# Lead Magnet Outline — \"30-Day AI Content Starter Kit\"\n\n"
        "1 sample newsletter + 2 short scripts + 7-day posting calendar (free).\n",
        f"{SAMPLE}_strategy_summary.md": "# Content Strategy Summary (sample)\n\nCadence, niches, channels, and a 30-day calendar.\n",
    }
    written = []
    for name, body in pieces.items():
        p = PACK_DIR / name
        p.write_text(body)
        written.append(p)
    return written


def register_assets(files: list[Path]) -> int:
    try:
        from lib import showroom_assets as SA
    except Exception:
        return 0
    n = 0
    for f in files:
        title = f.stem.replace("_", " ").title()
        SA.register("monetization_pack", title, str(f.relative_to(ROOT)),
                    showroom_path=str(f.relative_to(ROOT)), key=f.name, status="needs_review")
        n += 1
    return n


def main() -> int:
    ap = argparse.ArgumentParser(description="Nexus Monetization Scout")
    ap.add_argument("--analyze", help="source text to analyze as primary evidence")
    ap.add_argument("--file", help="path to a transcript/article file to analyze")
    ap.add_argument("--build-sample-pack", action="store_true")
    ap.add_argument("--notify", action="store_true")
    ap.add_argument("--dry-run", action="store_true", default=True)
    ap.add_argument("--send", action="store_true", help="manual Ray-only notify (overrides dry-run)")
    args = ap.parse_args()

    source = args.analyze or (Path(args.file).read_text(errors="ignore") if args.file and Path(args.file).exists() else "")

    if source:
        print(SCOUT.run_scout(source))
        print()

    if args.build_sample_pack:
        files = build_sample_pack()
        n = register_assets(files)
        print(f"\n[build] sample pack: {len(files)} draft files in {PACK_DIR.relative_to(ROOT)} · {n} reviewable assets registered (needs_review)")

    if args.notify:
        import subprocess
        cmd = [sys.executable, str(ROOT / "scripts" / "send_showroom_notification.py")]
        cmd.append("--send" if args.send else "--dry-run")
        print("[notify] running:", " ".join(c.split("/")[-1] for c in cmd))
        subprocess.run(cmd, cwd=str(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
