-- ── content_drafts ────────────────────────────────────────────────────────────
-- Content drafts generated by ContentWorker (social posts, newsletters).
-- Human review required before publishing.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists content_drafts (
  id          bigserial primary key,
  draft_type  text not null check (draft_type in ('social', 'newsletter', 'email', 'blog')),
  platform    text,                    -- "linkedin", "twitter", "email", etc.
  title       text,
  content     text not null,
  source_type text,                    -- "brief", "opportunity", "grant"
  source_id   bigint,                  -- optional ref to source row
  status      text default 'draft' check (status in ('draft', 'approved', 'published', 'rejected')),
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists content_drafts_status_idx     on content_drafts (status);
create index if not exists content_drafts_draft_type_idx on content_drafts (draft_type);
create index if not exists content_drafts_created_idx    on content_drafts (created_at desc);

create or replace function update_updated_at_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger content_drafts_updated_at
  before update on content_drafts
  for each row execute procedure update_updated_at_column();
