-- research_briefs.sql
-- Stores concise research briefs generated by Phase 6 Research Desk.
CREATE TABLE IF NOT EXISTS public.research_briefs (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title                 text NOT NULL,
  summary               text,
  priority              integer DEFAULT 5,
  brief_type            text,
  linked_hypothesis_id  uuid REFERENCES public.research_hypotheses(id) ON DELETE SET NULL,
  created_at            timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_research_briefs_brief_type ON public.research_briefs (brief_type);
CREATE INDEX IF NOT EXISTS idx_research_briefs_priority ON public.research_briefs (priority DESC);
CREATE INDEX IF NOT EXISTS idx_research_briefs_created_at ON public.research_briefs (created_at DESC);

COMMENT ON TABLE public.research_briefs IS 'Concise research briefs from Phase 6 — summaries, gap alerts, and strategy direction notes.';
