-- research_hypotheses.sql
-- Stores AI-generated research hypotheses from Phase 6 Research Desk.
CREATE TABLE IF NOT EXISTS public.research_hypotheses (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hypothesis_title     text NOT NULL,
  asset_type           text DEFAULT 'forex',
  market_type          text,
  hypothesis_text      text,
  supporting_evidence  jsonb DEFAULT '[]'::jsonb,
  novelty_score        numeric,
  plausibility_score   numeric,
  priority_score       numeric,
  linked_strategy_id   text,
  status               text DEFAULT 'candidate'
                         CHECK (status IN ('candidate','watchlist','promoted_for_testing','rejected')),
  trace_id             text,
  created_at           timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_research_hypotheses_status ON public.research_hypotheses (status);
CREATE INDEX IF NOT EXISTS idx_research_hypotheses_priority ON public.research_hypotheses (priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_research_hypotheses_asset_type ON public.research_hypotheses (asset_type);
CREATE INDEX IF NOT EXISTS idx_research_hypotheses_strategy ON public.research_hypotheses (linked_strategy_id);
CREATE INDEX IF NOT EXISTS idx_research_hypotheses_created_at ON public.research_hypotheses (created_at DESC);

COMMENT ON TABLE public.research_hypotheses IS 'Research hypotheses generated by Phase 6 — candidate ideas for strategy testing.';
COMMENT ON COLUMN public.research_hypotheses.status IS 'candidate | watchlist | promoted_for_testing | rejected';
