-- research_clusters.sql
-- Stores themed research clusters generated by Phase 6 Research Desk.
CREATE TABLE IF NOT EXISTS public.research_clusters (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cluster_name  text NOT NULL,
  theme         text NOT NULL,
  source_count  integer DEFAULT 0,
  summary       text,
  key_terms     jsonb DEFAULT '[]'::jsonb,
  confidence    numeric,
  created_at    timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_research_clusters_theme ON public.research_clusters (theme);
CREATE INDEX IF NOT EXISTS idx_research_clusters_created_at ON public.research_clusters (created_at DESC);

COMMENT ON TABLE public.research_clusters IS 'Themed research clusters from Phase 6 Research Desk — groups related artifacts/claims by topic.';
