-- strategy_optimizations.sql
-- Stores parameter improvement suggestions generated by the optimization lab.
-- All records are advisory only — no changes are applied automatically.
-- Safe to run multiple times (CREATE IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS public.strategy_optimizations (
  id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  strategy_id        text,       -- Strategy being optimized (null for system-level)
  asset_type         text        NOT NULL DEFAULT 'forex',
  optimization_type  text,       -- e.g. 'sl_tp', 'threshold', 'options_structure', 'confidence'
  parameter_name     text,       -- e.g. 'rr_ratio', 'approval_threshold', 'strike_otm_pct'
  original_value     numeric,    -- Current value (null if unknown/baseline)
  suggested_value    numeric,    -- Recommended value
  improvement_score  numeric,    -- 0-100: higher = more impactful suggestion
  notes              text,
  created_at         timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_strategy_optimizations_strategy_id
  ON public.strategy_optimizations (strategy_id);

CREATE INDEX IF NOT EXISTS idx_strategy_optimizations_asset_type
  ON public.strategy_optimizations (asset_type);

CREATE INDEX IF NOT EXISTS idx_strategy_optimizations_optimization_type
  ON public.strategy_optimizations (optimization_type);

CREATE INDEX IF NOT EXISTS idx_strategy_optimizations_parameter_name
  ON public.strategy_optimizations (parameter_name);

CREATE INDEX IF NOT EXISTS idx_strategy_optimizations_improvement_score
  ON public.strategy_optimizations (improvement_score DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_optimizations_created_at
  ON public.strategy_optimizations (created_at DESC);

-- Comments
COMMENT ON TABLE public.strategy_optimizations IS
  'Parameter improvement suggestions from the Nexus Optimization Lab. Advisory only — all suggestions require human review before implementation. Written by optimizer_writer.js.';

COMMENT ON COLUMN public.strategy_optimizations.strategy_id IS
  'Strategy identifier this optimization applies to. "system" for system-wide threshold suggestions.';

COMMENT ON COLUMN public.strategy_optimizations.asset_type IS
  'Asset class this optimization applies to: forex or options';

COMMENT ON COLUMN public.strategy_optimizations.optimization_type IS
  'Category of optimization: sl_tp (stop/take-profit), threshold (risk gates), options_structure (options params), confidence (AI calibration)';

COMMENT ON COLUMN public.strategy_optimizations.parameter_name IS
  'Name of the parameter being optimized (e.g. rr_ratio, approval_threshold, dte, strike_otm_pct)';

COMMENT ON COLUMN public.strategy_optimizations.original_value IS
  'Current parameter value at the time the optimization was generated. Null if baseline is unknown.';

COMMENT ON COLUMN public.strategy_optimizations.suggested_value IS
  'Data-driven recommended value for the parameter';

COMMENT ON COLUMN public.strategy_optimizations.improvement_score IS
  'Estimated improvement potential on a 0-100 scale. Higher = more impactful change. Based on gap between current and optimal parameter values.';

COMMENT ON COLUMN public.strategy_optimizations.notes IS
  'Detailed explanation of why this change is suggested, including supporting data';

-- Verify:
-- SELECT strategy_id, optimization_type, parameter_name,
--        original_value, suggested_value, improvement_score, notes, created_at
-- FROM public.strategy_optimizations
-- ORDER BY improvement_score DESC
-- LIMIT 20;
