-- ════════════════════════════════════════════════════════════════════════════
-- NEXUS AI — Supabase table setup (run once in SQL Editor)
-- Project: ftxbphwlqskimdnqcfxh
-- Dashboard: https://supabase.com/dashboard/project/ftxbphwlqskimdnqcfxh/sql
-- ════════════════════════════════════════════════════════════════════════════

-- ── Shared trigger function ────────────────────────────────────────────────
create or replace function update_updated_at_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── grant_opportunities ────────────────────────────────────────────────────
-- Surfaced by GrantWorker from research_artifacts (topic=grant_research)
create table if not exists grant_opportunities (
  id                   bigserial primary key,
  artifact_id          bigint references research_artifacts(id) on delete set null,
  source               text,
  title                text not null,
  program_name         text,
  funding_amount       text,
  geography            text,
  target_business_type text,
  eligibility_notes    text,
  deadline             text,
  confidence           decimal(4,3),
  score                integer default 0 check (score >= 0 and score <= 100),
  status               text default 'new' check (status in ('new', 'reviewed', 'applied', 'dismissed')),
  trace_id             text,
  created_at           timestamptz default now(),
  updated_at           timestamptz default now()
);

create index if not exists grant_opp_score_idx  on grant_opportunities (score desc);
create index if not exists grant_opp_status_idx on grant_opportunities (status);
create index if not exists grant_opp_geo_idx    on grant_opportunities (geography);

drop trigger if exists grant_opportunities_updated_at on grant_opportunities;
create trigger grant_opportunities_updated_at
  before update on grant_opportunities
  for each row execute procedure update_updated_at_column();

-- ── content_drafts ─────────────────────────────────────────────────────────
-- Social posts + newsletters generated by ContentWorker (draft, human-review)
create table if not exists content_drafts (
  id          bigserial primary key,
  draft_type  text not null check (draft_type in ('social', 'newsletter', 'email', 'blog')),
  platform    text,
  title       text,
  content     text not null,
  source_type text,
  source_id   bigint,
  status      text default 'draft' check (status in ('draft', 'approved', 'published', 'rejected')),
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists content_drafts_status_idx  on content_drafts (status);
create index if not exists content_drafts_type_idx    on content_drafts (draft_type);
create index if not exists content_drafts_created_idx on content_drafts (created_at desc);

drop trigger if exists content_drafts_updated_at on content_drafts;
create trigger content_drafts_updated_at
  before update on content_drafts
  for each row execute procedure update_updated_at_column();

-- ── business_opportunities: add artifact_id column (if not already there) ─
alter table business_opportunities
  add column if not exists artifact_id bigint references research_artifacts(id);

-- ── Force PostgREST schema cache reload ───────────────────────────────────
select pg_notify('pgrst', 'reload schema');

-- ── Verify ────────────────────────────────────────────────────────────────
select table_name from information_schema.tables
  where table_schema = 'public'
  and table_name in ('grant_opportunities', 'content_drafts')
  order by table_name;
